#!/usr/bin/env python3
# generate_groups.py -- v2.8 group-image package-list generator.
#
# Every chapter has its own package list (chapters/<stem>/packages_cran.txt,
# in this directory). v2.8 collapses the 50 chapters into 6 GROUP images
# (see groups.yaml) plus an autogenerated MONOLITH.
# A group's package list is generated -- not hand-maintained -- because it is
# a UNION over a set that itself changes: every time a chapter's own
# footprint changes, every group list containing that chapter must change
# with it. A hand-maintained union is exactly the kind of derived fact that
# drifts silently the moment one of its 8-11 inputs moves and nobody
# remembers to re-union it by hand; a generator makes "group list matches its
# members" a checked invariant (--check, below) instead of a hoped-for one.
# groups.yaml -- the actual chapter-to-group ASSIGNMENT -- stays hand-
# maintained, because that assignment is an editorial decision with no
# mechanical derivation; only the union arithmetic on top of it is generated.
#
# INPUTS (read-only):
#   groups.yaml                          -- hand-maintained group membership
#                                           (this dir)
#   chapters/<stem>/packages_cran.txt    -- each chapter's own FULL package
#                                           list (this dir; 50 files, one of
#                                           them empty -- see the NOTE on the
#                                           "errors" chapter below).
#                                           The 48 chapters that had a 2.7
#                                           image carry the list their 2.7
#                                           footprint capture produced, copied
#                                           here unchanged on 2026-09-02; gis
#                                           was captured the same way in 2.8.
#
# OUTPUTS (all generated; do not hand-edit, rerun this script instead):
#   groups/<group>/packages_cran.txt    (6 files, one per groups.yaml key)
#   monolith/packages_cran.txt          (1 file: union of the 6 group files)
#
# The monolith sits BESIDE groups/, not inside it. It is not a group: it
# renders no chapter and exists for the .devcontainer.json, so a `groups`
# path segment would make plan.py demand a `renders` list it cannot have
# (the 6 groups already claim all 50 chapters, and no .qmd may be claimed
# twice).
#
# METHOD: do NOT subtract the shared `common` base (common/packages_cran.txt)
# from anything here. v2.7's own chapter Dockerfiles
# install each chapter's FULL footprint on top of `common`, relying on pak's
# already-installed-package skip (dependencies=FALSE, exact-version match) to
# make that a true no-op for whatever common already covers -- which is what
# makes each v2.7 chapter image a strict superset of its footprint BY
# CONSTRUCTION (see archive/epirhandbook/2.6/generate.py's chapter_dockerfile
# docstring for the original statement of this property; v2.7 inherited it
# unchanged). A group list built by plain UNION of its members' full lists
# preserves that same superset property for free -- unioning supersets is
# still a superset of every member. Subtracting common first and re-adding it
# later would not be wrong on its own, but it is one extra derived step this
# script has no reason to take: nothing here needs the subtracted form.
#
# NOTE on the "errors" chapter: it has no executable R chunks, so its
# footprint IS the empty set and chapters/errors/packages_cran.txt is an
# empty file. A MISSING file is still a hard error (a typo'd or renamed
# stem must stop the run); an empty file is a chapter that needs nothing
# beyond common.
#
# DETERMINISM: package names are sorted with plain sorted() -- Python's
# default order is by Unicode code point, which for the ASCII-only package
# names here is byte-identical to the C-locale `sort` order the existing
# chapters/*/packages_cran.txt files already use (confirmed by
# `diff <(cat f) <(sort f)` against several of them before writing this).
# Groups themselves are also iterated in sorted-key order (not groups.yaml's
# own mapping order), so output never depends on YAML key ordering either.
# Nothing here reads wall-clock time, randomness, or directory-iteration
# order for its file CONTENTS -- os.listdir() is used only in the coverage
# check (check_coverage, below), and only to compare a SET against
# groups.yaml, never to decide any list's order. Re-running this script
# against unchanged inputs reproduces byte-identical output.
#
# CLI:
#   python3 generate_groups.py           # write the 7 files
#   python3 generate_groups.py --check   # regenerate in memory, diff against
#                                         # the committed files; exit 1 (with
#                                         # the diff, on stderr) on any
#                                         # difference. This is what CI runs.
import argparse
import difflib
import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
GROUPS_YAML = os.path.join(HERE, "groups.yaml")
CHAPTERS = os.path.join(HERE, "chapters")
GROUPS_OUT_DIR = os.path.join(HERE, "groups")



def load_groups(path):
    """groups.yaml -> {group_key: [stem, ...]}, in the file's own list order
    per group (irrelevant to the output -- packages are unioned into a set
    and re-sorted regardless of input order; see build())."""
    with open(path) as f:
        doc = yaml.safe_load(f)
    if not isinstance(doc, dict) or set(doc) != {"groups"}:
        raise ValueError(
            f"{path}: top level must be a mapping with exactly one key, "
            f"'groups', mapping to a non-empty mapping of group name -> "
            f"chapter-stem list; got {doc!r}"
        )
    groups = doc["groups"]
    if not isinstance(groups, dict) or not groups:
        raise ValueError(f"{path}: 'groups' must be a non-empty mapping; got {groups!r}")
    for key, stems in groups.items():
        if not isinstance(stems, list) or not stems or not all(
            isinstance(s, str) and s for s in stems
        ):
            raise ValueError(
                f"{path}: group {key!r} must map to a non-empty list of "
                f"non-empty chapter-stem strings; got {stems!r}"
            )
    return groups


def read_chapter_packages(stem):
    """<stem>'s own full package list: bare package names, one per line,
    no comments, no blank lines (true of all 49 files -- verified).

    A missing file is a HARD ERROR naming the stem and the exact path looked
    for. A typo'd stem in groups.yaml, or a chapter that has moved/been
    renamed under chapters/, must not be allowed to silently contribute zero
    packages to a group -- it must stop the run. An EMPTY file is legitimate
    (today: errors, which has no executable R chunks).
    """
    path = os.path.join(CHAPTERS, stem, "packages_cran.txt")
    if not os.path.isfile(path):
        raise ValueError(
            f"chapter stem {stem!r} (from groups.yaml) has no packages_cran.txt "
            f"-- looked for it at {path} and it does not exist. This is either "
            f"a typo'd stem in groups.yaml, or a chapter that has moved/been "
            f"renamed under {CHAPTERS} since groups.yaml was last updated. "
            f"(A chapter that needs nothing beyond `common`, like 'errors', "
            f"gets an EMPTY packages_cran.txt, never a missing one.)"
        )
    with open(path) as f:
        return [line.strip() for line in f if line.strip()]


def check_coverage(groups):
    """Fail on drift between groups.yaml and the real chapters/ directory
    listing, in EITHER direction:
      - a chapter dir on disk that no group claims -- a chapter silently
        dropping out of the v2.8 product, the exact failure this guards;
      - a group claiming a stem that is claimed by ANOTHER group too, or
        that does not exist on disk at all (typo, or upstream rename/removal
        groups.yaml was never updated for).
    """
    claimed = {}
    for key, stems in groups.items():
        for s in stems:
            if s in claimed:
                raise ValueError(
                    f"groups.yaml: chapter stem {s!r} is claimed by both "
                    f"group {claimed[s]!r} and group {key!r}. Every chapter "
                    f"must belong to exactly one group."
                )
            claimed[s] = key

    on_disk = {
        name
        for name in os.listdir(CHAPTERS)
        if os.path.isdir(os.path.join(CHAPTERS, name))
    }

    unclaimed = sorted(on_disk - set(claimed))
    if unclaimed:
        raise ValueError(
            f"{len(unclaimed)} chapter dir(s) under {CHAPTERS} are not "
            f"claimed by any group in groups.yaml: {unclaimed}. A "
            f"chapter silently dropping out of the v2.8 product is exactly "
            f"the failure this check exists to catch -- add it to a group "
            f"in groups.yaml."
        )

    phantom = sorted(set(claimed) - on_disk)
    if phantom:
        raise ValueError(
            f"groups.yaml claims {len(phantom)} chapter stem(s) that do not "
            f"exist as a directory under {CHAPTERS}: {phantom}. Typo, or "
            f"a chapter renamed/removed upstream without groups.yaml being "
            f"updated to match."
        )


def build(groups):
    """groups.yaml -> {output relative path: [sorted package names], ...}
    for all 7 outputs (6 groups + monolith). Pure computation, no filesystem
    writes -- both the write path and --check share this function, so the
    check can never drift from what a real run would actually produce."""
    check_coverage(groups)
    outputs = {}
    monolith = set()
    for key in sorted(groups):  # fixed key order, independent of groups.yaml
        pkgs = set()
        for stem in groups[key]:
            pkgs.update(read_chapter_packages(stem))
        outputs[f"groups/{key}/packages_cran.txt"] = sorted(pkgs)
        monolith.update(pkgs)
    outputs["monolith/packages_cran.txt"] = sorted(monolith)
    return outputs


def render(names):
    return "".join(f"{p}\n" for p in names)


def write_outputs(outputs):
    for rel, names in outputs.items():
        path = os.path.join(HERE, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(render(names))


def check(outputs):
    """Diff freshly-computed `outputs` against the COMMITTED files on disk.
    Returns a list of (relative_path, unified_diff_text) for every path that
    differs -- including a wanted file that is missing on disk, and a
    committed file under groups/ that `outputs` no longer wants at all (a
    stale file left over from a prior groups.yaml). Empty list = clean."""
    on_disk_rel = set()
    if os.path.isdir(GROUPS_OUT_DIR):
        for root, _dirs, files in os.walk(GROUPS_OUT_DIR):
            for fn in files:
                if fn != "packages_cran.txt":
                    continue          # Dockerfiles live here too; only the generated lists are ours
                full = os.path.join(root, fn)
                on_disk_rel.add(os.path.relpath(full, HERE))

    problems = []
    for rel in sorted(set(outputs) | on_disk_rel):
        full = os.path.join(HERE, rel)
        committed = None
        if os.path.isfile(full):
            with open(full) as f:
                committed = f.read()
        wanted = render(outputs[rel]) if rel in outputs else None
        if committed != wanted:
            diff = "".join(
                difflib.unified_diff(
                    (committed or "").splitlines(keepends=True),
                    (wanted or "").splitlines(keepends=True),
                    fromfile=f"{rel} (committed)",
                    tofile=f"{rel} (regenerated)",
                )
            )
            problems.append((rel, diff))
    return problems


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and diff against the committed files; "
        "exit 1 (with the diff, on stderr) on any difference. What CI runs.",
    )
    args = ap.parse_args()

    groups = load_groups(GROUPS_YAML)
    outputs = build(groups)

    if args.check:
        problems = check(outputs)
        if problems:
            for rel, diff in problems:
                print(f"--- DRIFT: {rel} ---", file=sys.stderr)
                print(diff, file=sys.stderr)
            print(
                f"generate_groups.py --check: {len(problems)} file(s) differ "
                f"from the committed output -- rerun 'python3 generate_groups.py' "
                f"and commit the result.",
                file=sys.stderr,
            )
            sys.exit(1)
        print(f"generate_groups.py --check: OK, {len(outputs)} files match committed output.")
        return

    write_outputs(outputs)
    print("group\tchapters\tpackages")
    for key in sorted(groups):
        n = len(outputs[f"groups/{key}/packages_cran.txt"])
        print(f"{key}\t{len(groups[key])}\t{n}")
    print(f"monolith\t{len(groups)} groups\t{len(outputs['monolith/packages_cran.txt'])}")


if __name__ == "__main__":
    main()
